import Head from 'next/head'
import Hero from 'components/Hero'
import Navbar from 'components/Navbar'
import TechStack from 'components/TechStack'
import Projects from 'components/Projects'
import Contact from 'components/Contact'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='main'>
        <div className='main-content'>
          <Navbar />
          <Hero />
          <TechStack />
          <Projects />
          <Contact />
        </div>
      </main>
    </>
  )
}
